learning-process/parallel_programming_course

scripts/run.bat
=> Time limit for gtest

CMakeLists.txt, cmake/FindTBB.cmake, cmake/TBBGet.cmake
Solve task [https://github.com/learning-process/parallel_programming_course/issues/14](https://github.com/learning-process/parallel_programming_course/issues/14)
=> TBB update version

scripts/run.sh
This PR is going to resolve #26
=> Fix run.sh

.github/workflows/main.yml
- Use `create-symlink` for automatic ccache to simplity PATH configuration
- Set up OpenMP and OpenSSL in less verbose way on macOS
=> Simpify CI jobs implementation

.github/workflows/main.yml, .github/workflows/static-analysis-pr.yml, .github/workflows/static-analysis.yml
- Make CMake configuration and build step set up in the same shorter way
- Remove additional step of submodules update and add it to actions/checkout
=> Unify and simplify build process in all CI actions

README.md
GitHub updated the path for workflow badges a long time ago: https://github.com/github/docs/pull/3802/files#diff-95d58394efa588c4f92f85274259efb8ca1e10a02bd346549e65b57604c156c4
Docs: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
Old link became outdated, and it shows old status all the time
=> Update badge link in README.md

modules/core/perf/func_tests/test_task.hpp, modules/core/task/func_tests/test_task.hpp, modules/core/task/include/task.hpp, modules/core/task/src/task.cpp, modules/ref/average_of_vector_elements/include/ref_task.hpp, modules/ref/max_of_vector_elements/include/ref_task.hpp, modules/ref/min_of_vector_elements/include/ref_task.hpp, modules/ref/most_different_neighbor_elements/include/ref_task.hpp, modules/ref/nearest_neighbor_elements/include/ref_task.hpp, modules/ref/num_of_alternations_signs/include/ref_task.hpp, modules/ref/num_of_orderly_violations/include/ref_task.hpp, modules/ref/sum_of_vector_elements/include/ref_task.hpp, modules/ref/sum_values_by_rows_matrix/include/ref_task.hpp, modules/ref/vector_dot_product/include/ref_task.hpp, tasks/mpi/example/include/ops_mpi.hpp, tasks/mpi/example/src/ops_mpi.cpp, tasks/omp/example/include/ops_omp.hpp, tasks/omp/example/src/ops_omp.cpp, tasks/seq/example/include/ops_seq.hpp, tasks/seq/example/src/ops_seq.cpp, tasks/stl/example/include/ops_stl.hpp, tasks/stl/example/src/ops_stl.cpp, tasks/tbb/example/include/ops_tbb.hpp, tasks/tbb/example/src/ops_tbb.cpp
Use 'impl' methods strategy to hide mandatory function calls. Task class child are adviced to override '*_impl' methods instead of public ones.
=> Hide 'internal_order_test' explicit launch for all tasks

README.md, tasks/mpi/example/func_tests/main.cpp, tasks/mpi/example/include/ops_mpi.hpp, tasks/mpi/example/src/ops_mpi.cpp, tasks/omp/example/func_tests/main.cpp, tasks/omp/example/include/ops_omp.hpp, tasks/omp/example/src/ops_omp.cpp, tasks/seq/example/src/ops_seq.cpp, tasks/stl/example/func_tests/main.cpp, tasks/stl/example/include/ops_stl.hpp, tasks/stl/example/src/ops_stl.cpp, tasks/tbb/example/func_tests/main.cpp, tasks/tbb/example/include/ops_tbb.hpp, tasks/tbb/example/src/ops_tbb.cpp
- move getRandomVector to func tests module
- clean up redundant code
=> Move test functions to the test modules in examples

tasks/CMakeLists.txt, tasks/mpi/example/func_tests/main.cpp, tasks/mpi/example/perf_tests/main.cpp, tasks/mpi/runner.cpp, tasks/omp/example/func_tests/main.cpp, tasks/omp/example/perf_tests/main.cpp, tasks/omp/runner.cpp, tasks/seq/example/func_tests/main.cpp, tasks/seq/example/perf_tests/main.cpp, tasks/seq/runner.cpp, tasks/stl/example/func_tests/main.cpp, tasks/stl/example/perf_tests/main.cpp, tasks/stl/runner.cpp, tasks/tbb/example/func_tests/main.cpp, tasks/tbb/example/perf_tests/main.cpp, tasks/tbb/runner.cpp
It will be possible to copy example without thinking about deleting main, and it will be easier to modify runners, for example, inject custom test listeners by modifying a single file.
=> Extract main() from example projects

scripts/create_perf_table.py
Print a warning instead
close https://github.com/learning-process/parallel_programming_course/issues/177
=> Fix perf table creation failure in case expected test is not found

.github/workflows/main.yml
Split to basic and extended jobs:
- basic: MPI + threads with count 1-4
- extended: threads with count (5-16)
Preparation for https://github.com/learning-process/parallel_programming_course/issues/176
=> [CI] Split long build + test CI jobs

.github/workflows/main.yml
close https://github.com/learning-process/parallel_programming_course/issues/213
=> [CI] Use gcovr instead of lcov for codecov

tasks/all/runner.cpp, tasks/tbb/runner.cpp
close https://github.com/learning-process/parallel_programming_course/issues/180
=> Bind TBB max threads num to OMP_NUM_THREADS environment variable value

scoreboard/index.html, scoreboard/main.py, scoreboard/static/main.css
Initial version of https://github.com/learning-process/parallel_programming_course/issues/112
=> Implement basic version of scoreboard

.clang-tidy
- Use correct option to manage excluded headers in misc-include-cleaner diagnostic
- Enable back default 'clang-analyzer-optin.cplusplus.UninitializedObject' diagnostic
=> Fix headers config in .clang-tidy

.yamllint
Suppress useless warnings to clean up GitHub "Files changed" page output
=> Suppress useless warnings in .yamllint

scoreboard/main.py
Address scoreboard comments from #295
=> Adjust scoreboard columns

.github/workflows/pages.yml, CMakeLists.txt, cmake/boost.cmake, cmake/gtest.cmake, cmake/opencv.cmake, cmake/scoreboard.cmake, modules/CMakeLists.txt, scoreboard/CMakeLists.txt, scoreboard/main.py
- Adjust CMake implementation to be able to build without USE_<MPI/OMP/STL/TBB>
- Use CMake to build scoreboard instead of running Python script directly
=> Use cmake to build scoreboard

docs/conf.py
Solve the problem when part of ToC disappears on the left pane on some pages
=> [docs] Enforce the same lest pane template in sphinx config

modules/core/perf/func_tests/test_task.hpp
This seems to be known issue in clang: https://github.com/llvm/llvm-project/issues/98122
Provide a workaround for that
=> Fix clang-tidy behavior with 'chrono' headers

.clang-tidy
resolves https://github.com/learning-process/parallel_programming_course/issues/338
=> Forbid C-style casts using clang-tidy

scripts/generate_perf_results.sh
Fail when run_tests.py script execution fails
=> Enable 'pipefail' in scripts/generate_perf_results.sh

.clang-tidy, tasks/mpi/example/src/ops_mpi.cpp
Functions with scores beyond 15 are typically flagged as potentially problematic. Empirical evidence suggests that such functions are more likely to correlate with higher error rates or maintenance challenges. It becomes increasingly hard for developers to follow the control flow, and these functions are prime candidates for refactoring into simpler, more modular parts.
=> Make readability-function-cognitive-complexity threshold more strict

.github/workflows/static-analysis-pr.yml
Forbid `NOLINT*` comments usage
=> [CI] Enable automatic NOLINT check

scripts/run_tests.py
`--gtest_also_run_disabled_tests` can't work with `std::terminate`
=> Fix sanitizer

.clang-tidy
Enable enforcing the following clang-tidy checks so they’re enforced again:
- cppcoreguidelines-avoid-goto
- misc-no-recursion
- misc-unused-parameters
- readability-named-parameter
=> Re-enable selected clang-tidy diagnostics

.clang-tidy
Also remove OpenCV headers exclusion for misc-include-cleaner
=> Enable 'bugprone-exception-escape' and 'misc-header-include-cycle' clang-tidy checks

.github/workflows/main.yml, scripts/create_perf_table.py, scripts/run_tests.py
Backport necessary commits from ppc-2025-threads repo
=> Apply fixes for test scripts

.github/workflows/main.yml, docs/index.rst, docs/locale/en/LC_MESSAGES/user_guide/environment_variables.po, docs/locale/ru/LC_MESSAGES/user_guide/environment_variables.po, docs/user_guide/environment_variables.rst, modules/core/util/func_tests/util_tests.cpp, modules/core/util/src/util.cpp, scripts/create_perf_table.py, scripts/run_tests.py
- Use `PPC_` prefix for all used environment variables
- Add environment variables documentation page
=> Unify environment variables usage across the project

modules/core/performance/tests/perf_tests.cpp, modules/core/task/include/task.hpp
- mention the settings file path when GetStringTaskType fails to open the file
- add a unit test validating that the thrown message contains the missing path
=> Include path in GetStringTaskType error

modules/core/task/include/task.hpp, modules/core/util/include/util.hpp
- Add `PPC_FUNC_NAME` macro providing compiler agnostic pure function name
- Replace `__builtin_FUNCTION()` with `PPC_FUNC_NAME` macro in `task.hpp`
=> Add portable function name helper

modules/core/task/include/task.hpp, modules/core/task/tests/.clang-tidy, modules/core/task/tests/task_tests.cpp
- Avoid invalid iterators in `IsFullPipelineStage`
- Test premature `PostProcessing` calls
=> Fix pipeline stage check and add tests

modules/core/util/tests/util.cpp
Get rid of concurrent writing by multiple threads
=> Fix test for unset `PPC_NUM_THREADS` environment variable

.github/actions/setup-windows-toolchain/action.yml, .github/workflows/windows.yml
- add `.github/actions/setup-windows-toolchain` composite action
- use this new action in all Windows jobs to configure MSVC and tooling
=> [CI] Introduce shared Windows toolchain setup action

scripts/generate_perf_results.sh
- add a `#!/usr/bin/env bash` shebang
- enable `set -euo pipefail` for stricter error handling
=> Add shebang and strict mode to perf script

.github/workflows/mac.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, scripts/run_tests.py
- Extend `run_tests.py` to accept a list of counts and loop internally
- Collapse repeated CI test steps in workflow files by providing all counts in a single call
- Refactor main logic in `run_tests.py` into a helper to remove duplication
- Print each count before execution in batch mode
=> Allow batch test counts

.github/workflows/ubuntu.yml, docs/locale/en/LC_MESSAGES/user_guide/build.po, docs/locale/ru/LC_MESSAGES/user_guide/build.po, docs/user_guide/build.rst
- Build sanitizer tests with RelWithDebInfo
- Document that RelWithDebInfo is recommended for sanitizers/valgrind
=> Use RelWithDebInfo for sanitizers, document build types

.github/workflows/main.yml, .github/workflows/pages.yml, README.md
- Deploy coverage to GitHub Pages
- Link to coverage report in the README
- Reuse existing coverage artifact for deployment
resolves #329
=> [CI] Deploy coverage pages

docs/_static/custom.css, docs/conf.py
- import PT Sans from Google Fonts in custom CSS for `/ru` docs
- keep Sphinx setup that loads this stylesheet
=> [doc] Use Google-hosted PT Sans for Russian docs

modules/util/include/func_test_util.hpp, modules/util/include/perf_test_util.hpp
- drop `using namespace ppc::task` from func/perf test headers
- drop `using namespace ppc::performance` from perf test header
- qualify names in util helpers with their namespaces
=> Remove namespace directives from util headers

modules/task/tests/task_tests.cpp
- add a `ScopedFile` RAII helper for test files
- remove any temporary files in `task_tests.cpp`
=> Ensure test cleanup via RAII

docs/conf.py, scoreboard/main.py, scripts/create_perf_table.py, scripts/run_tests.py, scripts/variants_generation.py
Pre-requisite for https://github.com/learning-process/parallel_programming_course/pull/538
=> Address ruff linter remarks

scoreboard/data/threads-config.yml, scoreboard/main.py, scoreboard/templates/index.html.j2
- extend config with efficiency parameters and deadlines
- compute efficiency and deadline penalties in scoreboard
- show them in the HTML template
=> [scoreboard] Add efficiency and deadline scoring

CMakeLists.txt, modules/CMakeLists.txt
- reduce cmake boilerplate for 3rdparty includes
- compact third-party link statements for modules
=> Simplify dependency includes

.github/workflows/perf.yml
close https://github.com/learning-process/parallel_programming_course/issues/197
=> [CI] Add perf collector job for macOS

.github/workflows/docker.yml
- pre-commit job only build the docker image to verify whether it is working well
- post-commit stage (on master branch only) builds the final version and pushes to the registry under the `latest` version
=> [CI] Build up-to-date Docker image version on pre-commit

cmake/functions.cmake, tasks/CMakeLists.txt
Introduced a cache variable `PPC_IMPLEMENTATIONS` in the student tasks CMake configuration, so implementations can be customized during CMake configuration
=> Introduce PPC_IMPLEMENTATIONS variable

.devcontainer/devcontainer.json, .github/actions/clang-tidy-native/action.yml, .github/workflows/docker.yml, .github/workflows/perf.yml, .github/workflows/pre-commit.yml, .github/workflows/static-analysis-pr.yml, .github/workflows/ubuntu.yml, docker/ubuntu.Dockerfile
- Update LLVM version from 20 to 21
- Update gtest to pick commit with the WA for clang-21:  https://github.com/google/googletest/commit/fa8438ae6b70c57010177de47a9f13d7041a6328
=> [CI] Switch to LLVM 21
